#pragma once
enum ResourceSpecification : size_t {
    OBJECT_TRANSFORM_DATA = 0,
    CAMERA_DATA,
    NORMAL_MAP,
    DIFFUSE_MAP,
    ROURGHNESS_MAP,
    METALLIC_MAP,
    AMBIENT_OCCLUSION_MAP,
    ROUGHNESS_METALLIC_AMBIENT_OCCLUSION_MAP
};
